/**
 * Extension Point initial generated by Mod4j at: Sun Apr 12 22:00:42 CEST 2009
 */
package org.company.recordshop.bd.domain.businessrules;

import org.company.recordshop.bd.domain.OrderLine;
import org.springframework.validation.Errors;

/**
 * 
 * 
 * This ExtensionPoint is intended to be manually changed by developers.
 * 
 */
public class CheckProductMinimumQuantity extends CheckProductMinimumQuantityImplBase {

    /**
     * Validates if the quantity for the OrderLine matches the minimal quantity of the associated Product.
     */
    public void validate(Object target, Errors errors) {

        // CheckProductMinimumQuantity.
        OrderLine orderline = (OrderLine) target;

        if (orderline.getProduct() != null) {

            if (orderline.getQuantity() < orderline.getProduct().getMinimalQuantity()) {
                errors.rejectValue("quantity", "orderline.invalid.quantity", null,
                        "The minimal quantity for this Product is:" + orderline.getProduct().getMinimalQuantity());
            }
        }
    }

}
