/*
 * generated by Xtext
 */
package org.mendix.dsl.businessdomain.xtext;

import org.eclipse.xtext.ui.common.editor.syntaxcoloring.ILexicalHighlightingConfiguration;
import org.mendix.dsl.businessdomain.xtexthighlighting.BusinessDomainLexicalHighlightingConfiguration;
/**
 * Use this class to register components to be used within the IDE.
 */
public class BusinessDomainUiModule extends org.mendix.dsl.businessdomain.xtext.AbstractBusinessDomainUiModule {

    public Class<? extends ILexicalHighlightingConfiguration> bindILexicalHighlightingConfiguration() {
        return BusinessDomainLexicalHighlightingConfiguration.class;
    }

}
