/*
* generated by Xtext
*/
package org.mendix.dsl.service.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ServiceAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/mendix/dsl/service/xtext/parser/antlr/internal/InternalService.tokens");
	}
}
