/*
 * generated by Xtext
 */
package org.mendix.dsl.datacontract.xtext;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DataContractRuntimeModule extends org.mendix.dsl.datacontract.xtext.AbstractDataContractRuntimeModule {

	// contributed by org.eclipse.xtext.generator.validation.CheckFragment
	@org.eclipse.xtext.service.SingletonBinding(eager=true)	public Class<? extends org.mendix.dsl.datacontract.xtext.validation.DataContractCheckValidator> bindDataContractCheckValidator() {
		return org.mendix.dsl.datacontract.xtext.validation.MyDataContractCheckValidator.class;
	}

}
