/*
 * generated by Xtext
 */
package org.mendix.dsl.businessdomain.xtext;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BusinessDomainRuntimeModule extends org.mendix.dsl.businessdomain.xtext.AbstractBusinessDomainRuntimeModule {

	// contributed by org.eclipse.xtext.generator.validation.CheckFragment
	@Override
	@org.eclipse.xtext.service.SingletonBinding(eager=true)	public Class<? extends org.mendix.dsl.businessdomain.xtext.validation.BusinessDomainCheckValidator> bindBusinessDomainCheckValidator() {
		return org.mendix.dsl.businessdomain.xtext.validation.MyBusinessDomainCheckValidator.class;
	}

	// Our own lazy linker, workaround for bugzilla  282486: opposite references not set correctly
	@Override
	public Class<? extends org.eclipse.xtext.linking.ILinker> bindILinker() {
		return BusinessDomainLazyLinker.class;
	}

}
