/**
 * Extension point generated initially by Mod4j BusinessDomain DSL by BeanClassExtensionPoint in NewJavaBean.xpt at: Sat Mar 07 22:20:49 CET 2009
 */
package org.company.recordshop.bd.domain;

import org.joda.time.DateTime;

/**
 * Test derived attributes
 * 
 * @author Generated by Mod4j BusinessDomain DSL
 */
@SuppressWarnings("serial")
public class DerivedNotYetImplemented extends DerivedNotYetImplementedImplBase {

	/**
	 * Minimal constructor for DerivedNotYetImplemented
	 */
	public DerivedNotYetImplemented(

	) {
		super(

		);
	}

	protected DerivedNotYetImplemented(Long id) {
	    super(id);
    }

    /**
	 * @return first (String)
	 */
	public String getFirst() {
		throw new UnsupportedOperationException("Not implemented");
	}

	/**
	 * 
	 * @return secondo (boolean)
	 */
	public Boolean isSecondo() {
		throw new UnsupportedOperationException("Not implemented");
	}

	/**
	 * @return third (DateTime)
	 */
	public DateTime getThird() {
		throw new UnsupportedOperationException("Not implemented");
	}

	/**
	 * @return fourth (int)
	 */
	public Integer getFourth() {
		throw new UnsupportedOperationException("Not implemented");
	}

	/**
	 * @return fifth (float)
	 */
	public Float getFifth() {
		throw new UnsupportedOperationException("Not implemented");
	}

	/**
	 * @param first
	 *            (String)
	 */
	public void setFirst(final String first) {
		throw new UnsupportedOperationException("Not implemented");
	}

	/**
	 * @param secondo
	 *            (boolean)
	 */
	public void setSecondo(final Boolean secondo) {
		throw new UnsupportedOperationException("Not implemented");
	}

	/**
	 * @param third
	 *            (DateTime)
	 */
	public void setThird(final DateTime third) {
		throw new UnsupportedOperationException("Not implemented");
	}

	/**
	 * @param fourth
	 *            (int)
	 */
	public void setFourth(final Integer fourth) {
		throw new UnsupportedOperationException("Not implemented");
	}

	/**
	 * @param fifth
	 *            (float)
	 */
	public void setFifth(final Float fifth) {
		throw new UnsupportedOperationException("Not implemented");
	}

}
