
/**
 * Extension point, initially generated by Mod4j. 
 *     Time             : Sat Sep 25 17:39:31 CEST 2010
 *     Application model: Owner
 *     Generator        :  Mod4j BusinessDomainDsl generator: NewJavaBean.xpt
 *
 * It is intended to customize and maintain this file by hand. 
 * If you remove this file, it will be regenerated by Mod4j to its original state.
 */

package org.company.recordshop.bd.domain;

/**
 * 
 *
 * @author Generated by Mod4j BusinessDomain DSL
 */
public class Owner extends OwnerImplBase {

	/**
	 * Default no-argument constructor for Owner
	 */
	protected Owner() {

	}

	/**
	 * Minimal constructor for Owner
	 * @param name (String) 
	 */
	public Owner(String name) {
		super(name);
	}

	/**
	 * Creates a Owner with the specified ID.
	 */
	protected Owner(Long id) {
		super(id);
	}

}
